name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  playwright-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps chromium
    - name: Run Playwright tests
      run: yarn test:saucedemo
      env:
        SAUCE_USER: ${{ vars.SAUCE_USER }}
        SAUCE_LOCKED_USER: ${{ vars.SAUCE_LOCKED_USER }}
        SAUCE_PASSWORD: ${{ vars.SAUCE_PASSWORD }}
    - name: Deploy HTML report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ !cancelled() }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./playwright-report